site_name: Lampe Documentation
site_description: Lampe - LLM-powered code analysis and documentation tools
site_author: montagne-dev
site_url: https://docs.montagne.dev
repo_url: https://github.com/montagne-dev/lampe

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

copyright: Copyright &copy; 2024 montagne-dev
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/montagne-dev/lampe

nav:
  - Home: index.md
  - LampeSDK:
      - Overview: lampe-sdk/index.md
      - Core: lampe-sdk/core.md
      - CLI: lampe-sdk/cli.md
      - Describe: lampe-sdk/describe.md
      - Template: lampe-sdk/template.md
  - LampeCI:
      - Overview: lampe-ci/index.md
      - GitHub Actions: lampe-ci/github-actions.md
      - Bitbucket Pipelines: lampe-ci/bitbucket-pipelines.md
      - GitLab CI: lampe-ci/gitlab-ci.md
  - LampeCLI:
      - Overview: lampe-cli/index.md
      - CLI: lampe-cli/cli.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - Reference: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src, packages/**/src]
          options:
            show_source: true
            show_signature_annotations: true
            show_if_no_docstring: false
            show_bases: true
            show_root_heading: true
            docstring_style: numpy
            merge_init_into_class: true
